publishDir = "development"
buildDrafts = true
buildFuture = true
baseURL = "https://heavywatal.github.io/"
title = "Heavy Watal"
defaultContentLanguage = ""
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]
uglyURLs = true
pluralizeListTitles = false
titleCaseStyle = "none"
copyright = "(ɔ) 2008 岩嵜航 Watal M. Iwasaki"

[author]
name = "Watal M. Iwasaki"
twitter = "@heavywatal"

[params]
logo_src = "heavywatal.svg"
logo_alt = "岩嵜航"
theme_color = "#eeeeee"
og_image = "https://avatars.githubusercontent.com/heavywatal"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[module]
workspace = "hugo.work"
[[module.imports]]
path = "github.com/heavywatal/hugo-theme-nonblog"

[taxonomies]
tag = "tags"
