publishDir = "development"
buildDrafts = true
buildFuture = true
baseURL = "https://heavywatal.github.io/"
title = "Heavy Watal"
defaultContentLanguage = "ja"
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]
uglyURLs = true
pluralizeListTitles = false
titleCaseStyle = "none"
copyright = "(ɔ) 2008 岩嵜航 Watal M. Iwasaki"

[params]
logo_src = "heavywatal.svg"
logo_alt = "岩嵜航"
theme_color = "#eeeeee"
og_image = "https://avatars.githubusercontent.com/heavywatal"

[params.author]
name = "Watal M. Iwasaki"

[params.social]
twitter = "@heavywatal"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
footnote = false

[markup.highlight]
noClasses = false

[module]
[[module.imports]]
path = "github.com/heavywatal/hugo-theme-nonblog"

[taxonomies]
tag = "tags"
