[[main]]
    name = "R stats"
    identifier = "rstats"
    weight = 10
[[main]]
    name = "Python"
    identifier = "python"
    weight = 20
[[main]]
    name = "C++"
    identifier = "cxx"
    weight = 30
[[main]]
    name = "Biology"
    identifier = "bio"
    weight = 40
[[main]]
    name = "Developer Tools"
    identifier = "dev"
    weight = 50
[[main]]
    name = "Mac"
    identifier = "mac"
    weight = 70
[[main]]
    name = "Lectures"
    identifier = "lectures"
    weight = 80
[[main]]
    name = "Miscellaneous"
    identifier = "misc"
    weight = 90
[[main]]
    name = "Tags"
    url = "/tags.html"
    weight = 100
