baseURL = "https://heavywatal.github.io/"
title = "Heavy Watal"
theme = "nonblog"
languageCode = "ja"
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]
editor = "atom"
uglyURLs = true
googleAnalytics = "UA-41178626-2"

[blackfriday]
fractions = false
plainIDAnchors = true

[params]
author = "Watal M. Iwasaki"
base_path = "/"
logo_src = "heavywatal.svg"
logo_alt = "岩嵜航"
theme_color = "#e08010"
copyrights = "(ɔ) 2008 岩嵜航 Watal M. Iwasaki"
highlightjs_languages = ["sh", "c++", "python", "r", "tex"]
google_cse = "002893183080310956056:l56ddnprf-g"
og_image = "https://avatars.githubusercontent.com/heavywatal"

[taxonomies]
tag = "tags"

[[menu.main]]
    name = "R stats"
    identifier = "rstats"
    weight = 10
[[menu.main]]
    name = "Python"
    identifier = "python"
    weight = 20
[[menu.main]]
    name = "C++"
    identifier = "cxx"
    weight = 30
[[menu.main]]
    name = "Biology"
    identifier = "bio"
    weight = 40
[[menu.main]]
    name = "Developer Tools"
    identifier = "dev"
    weight = 50
[[menu.main]]
    name = "Linux"
    identifier = "linux"
    weight = 60
[[menu.main]]
    name = "Mac"
    identifier = "mac"
    weight = 70
[[menu.main]]
    name = "Lectures"
    identifier = "lectures"
    weight = 80
[[menu.main]]
    name = "Miscellaneous"
    identifier = "misc"
    weight = 90
[[menu.main]]
    name = "Tags"
    url = "/tags.html"
    weight = 100
