baseURL = "https://heavywatal.github.io/"
title = "Watal M. Iwasaki"
theme = "nonblog"
languageCode = "ja"
hasCJKLanguage = true
noTimes = true
disableRSS = true
editor = "atom"
uglyURLs = true
googleAnalytics = "UA-41178626-2"

[blackfriday]
fractions = false
plainIDAnchors = true

[params]
base_path = "/"
logo_src = "favicon-192x192.png"
logo_alt = "岩嵜航"
copyrights = "(ɔ) 2008 岩嵜航 Watal M. Iwasaki"
page_source = false
highlightjs_languages = ["sh", "c++", "python", "r", "tex"]

[taxonomies]
tag = "tags"

[[menu.main]]
    name = "R stats"
    identifier = "rstats"
    weight = 10
[[menu.main]]
    name = "Python"
    identifier = "python"
    weight = 20
[[menu.main]]
    name = "C++"
    identifier = "cxx"
    weight = 30
[[menu.main]]
    name = "Biology"
    identifier = "bio"
    weight = 40
[[menu.main]]
    name = "Developer Tools"
    identifier = "dev"
    weight = 50
[[menu.main]]
    name = "Linux"
    identifier = "linux"
    weight = 60
[[menu.main]]
    name = "Mac"
    identifier = "mac"
    weight = 70
[[menu.main]]
    name = "Lectures"
    identifier = "lectures"
    weight = 80
[[menu.main]]
    name = "Miscellaneous"
    identifier = "misc"
    weight = 90
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 100
